---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/tridentctl version --client
    register: trident_test_output
  - name: tridentctl version --client
    debug:
      msg: '{{ trident_test_output.stdout }}'
