---
- name: Testing andrewrothstein.trident
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'tridentctl version --client'
      ansible.builtin.command: /usr/local/bin/tridentctl version --client
      changed_when: false
      register: trident_test_output
    - name: Output of 'tridentctl version --client'
      ansible.builtin.debug:
        msg: '{{ trident_test_output.stdout }}'
